server:
  port: 9000
  servlet:
    context-path: /demo200909

value: abc

person:
  userName: kevin
  age: 21

personA:
  name: karry
  age: 20

arrays:
  - array1: a
    son1: 1
  - array2: b
    son1: 1