
#https://blog.csdn.net/jywhpu0612/article/details/105827327/
server:
  port: 8080  #端口号
  servlet:
    context-path: /shop #项目名称
spring:
  datasource:
    username: kevin
    password: Karry0921
    url: jdbc:mysql://bj.kevinkda.cn:3306/HuangSir?characterEncoding=utf-8&useSSl=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    charset: utf-8 #编码方式
    check-template-location: true #检查模板位置是否存在
    content-type: text/html
    enabled: true #是否启用freemarker
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates
    settings:
      classic_compatible: true

    #mvc:
    #  static-path-pattern: /static/**  #项目中访问静态资源的前缀名
    #resources:
    #  static-locations: classpath:/D:/img
    #static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload/


#配置mybatis
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.chinasoft.shop.domain
#通配符

#配置模板引擎
